# Generated by Django 5.1.4 on 2025-01-16 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("MediplusApp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="bookAppointment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=100)),
                ("phone_no", models.CharField(max_length=12)),
                ("date", models.DateField()),
                ("created_date", models.DateField(auto_now_add=True)),
                (
                    "department",
                    models.CharField(
                        choices=[
                            ("Cardiology", "Cardiology"),
                            ("Neurology", "Neurology"),
                            ("Orthopedics", "Orthopedics"),
                            ("Pediatrics", "Pediatrics"),
                            ("General Medicine", "General Medicine"),
                        ],
                        max_length=100,
                    ),
                ),
                (
                    "doctors_name",
                    models.CharField(
                        choices=[
                            ("Dr.Uday Rasal", "Dr.Uday Rasal"),
                            ("Dr.Payal Chavan", "Dr.Payal Chavan"),
                            ("Dr.Trupti Kupekar", "Dr.Trupti Kupekar"),
                            ("Dr.Ashish Sarule", "Dr.Ashish Sarule"),
                        ],
                        max_length=150,
                    ),
                ),
                ("message", models.TextField()),
            ],
        ),
    ]
